[package]
name = "gltf2hm"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "1.0.7"
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
gltf = "1.4.0"
image = "0.24.7"
nalgebra = "0.32.3"
rayon = "1.8.0"

[profile.dev.package.gltf]
opt-level = 3
